### ISSUE TITLE
I couldn't execute `forge.sh` that is included in the zip file is attached to releases

### ISSUE THREAD

**Issue by taiju** [fsprojects/Forge#99] opened 2016-04-23 05:16 UTC
I tried [this guide](http://fsprojects.github.io/Forge/#Installation) on Ubuntu Linux.

But I couldn't execute `forge.sh` that is included in the zip file is attached to the releases.

## Expected Behavior
1. Download the forge.zip from [the release](https://github.com/fsprojects/Forge/releases/tag/0.7.0).
2. Extract the forge.zip.
3. Add Forge location to PATH.
4. Can execute `forge.sh`.

## Current Behavior
Can't execute `forge.sh`.

## Possible Solution
It had two problem.

1. The `forge.sh` is not executable (644).
2. The `forge.sh` file format is `CR + LF`. (but it in repository is `LF`)

It might be document problem.

**Comment by mclang** [comment] 2016-05-10 08:28
The solution may be obvious, but I post it anyways:
```
$ chmod ugo+x forge.sh
$ dos2unix for.sh
```
Of course this **should** be fixed in the installation package...

**Comment by taiju** [comment] 2016-05-10 12:52
Thank you. I'm not in trouble, but it is a little troublesome...

**Comment by Krzysztof-Cieslak** [comment] 2016-05-10 16:20
It's probably already fixed (testing appreciated) but latest zip release is bit old.

**Comment by mclang** [comment] 2016-05-11 10:23
I tested 1.0.0-alpha-002.

The same CRLF problem seems still exist in the zip file.

**Comment by spencerwi** [comment] 2016-06-15 12:14
I've seen this happen too, and I dunno what the cause is. When I build from source on my Linux box, I get a valid, LF-only `forge.sh`. Maybe machine generating the zip release is Windows and absolutely doesn't want to create an LF-only file (even when just copying an existing LF-only one?)

**Comment by Krzysztof-Cieslak** [comment] 2016-06-15 17:21
Release process is coping files from https://github.com/fsprojects/Forge/tree/master/runners.

**Comment by spencerwi** [comment] 2016-07-16 13:36
I sent a PR to make sure that the git index had `forge.sh` marked as executable. I'm not 100% sure how that'll work when cloning and building from a Windows box, but it should work, I would think.

**Closed** 2016-07-27 17:13 UTC
